services:
  - type: web
    name: pdf-4u-online
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    plan: free
    healthCheckPath: /health
    domains:
      - pdf-4u.online
